name: Compile assets

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install NPM dependencies
        run: yarn

      - name: Compile assets
        run: yarn build

      - name: Commit compiled files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compile Assets
          file_pattern: public/
