name: Quality

on:
  push:
    branches:
      - livewire
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup
        uses: ./.github/actions/setup
      - name: 🔮 Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: 🕵️‍♂️ Run Laravel Pint
        run: composer test:lint
      - name: 🕵️‍♂️ Run Types
        run: composer test:types
